name: rapid_opt
channels:
  - defaults
dependencies:
  - python=3.9
  - pandas=1.2.4
  - ipython
  - ipykernel
  - scikit-learn
  - seaborn
  - pip
  - pip:
      - emukit==0.4.9
      - gpy==1.10.0
      - pydoe==0.3.8
      - numpy==1.21.0
      - scipy==1.10.0